/**
 * appleTheme — Apple's design language expressed as an Astryx theme.
 *
 * Source of truth: `apple/DESIGN.md`, generated by
 *   npx getdesign@latest add apple
 *
 * Every value below traces back to a token in that file. Nothing here is
 * invented, and nothing is written as a raw override in a stylesheet: accent
 * and brand surfaces belong in the theme (see AGENTS.md → ASTRYX rules).
 *
 * Extending `@astryxdesign/theme-neutral` keeps the status/categorical palettes
 * (success, error, warning, red/teal/…) intact so we only restate the Apple
 * surfaces, ink, hairlines, one accent blue, radii, and one shadow.
 */

import { defineTheme } from '@astryxdesign/core/theme';
import { neutralTheme } from '@astryxdesign/theme-neutral/built';

/** SF Pro first (real thing on Apple platforms), Inter as the open substitute. */
const SF_TEXT = 'SF Pro Text';
const SF_DISPLAY = 'SF Pro Display';
const SF_FALLBACKS =
  '-apple-system, BlinkMacSystemFont, "Inter", system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif';
const MONO_FALLBACKS =
  '"SF Mono", ui-monospace, Monaco, Consolas, "Liberation Mono", "Courier New", monospace';

type TokenTuple = string | [light: string, dark: string];

/**
 * Theme-family-local properties. These are the Apple-specific surfaces that
 * have no Astryx core equivalent (the near-black product tiles, the true-black
 * global nav, the one product shadow).
 */
const appleLocalTokens: Record<string, TokenTuple> = {
  // Surfaces
  '--astryx-theme-apple-color-black': ['#000000', '#000000'],
  '--astryx-theme-apple-color-parchment': ['#f5f5f7', '#000000'],
  '--astryx-theme-apple-color-pearl': ['#fafafc', '#1d1d1f'],
  '--astryx-theme-apple-color-tile-dark': ['#272729', '#1d1d1f'],
  '--astryx-theme-apple-color-tile-dark-2': ['#2a2a2c', '#232325'],
  '--astryx-theme-apple-color-tile-dark-3': ['#252527', '#161617'],
  // Ink
  '--astryx-theme-apple-color-ink': ['#1d1d1f', '#f5f5f7'],
  '--astryx-theme-apple-color-ink-muted-80': ['#333333', '#d0d0d2'],
  '--astryx-theme-apple-color-ink-muted-48': ['#7a7a7a', '#a1a1a6'],
  '--astryx-theme-apple-color-body-on-dark': ['#ffffff', '#ffffff'],
  '--astryx-theme-apple-color-body-muted-on-dark': ['#cccccc', '#cccccc'],
  // Hairlines
  '--astryx-theme-apple-color-hairline': ['#e0e0e0', '#424245'],
  '--astryx-theme-apple-color-divider-soft': ['#f0f0f0', '#2f2f31'],
  '--astryx-theme-apple-color-chip-translucent': ['#d2d2d7', '#424245'],
  // The single accent
  '--astryx-theme-apple-color-blue': ['#0066cc', '#2997ff'],
  '--astryx-theme-apple-color-blue-focus': ['#0071e3', '#2997ff'],
  '--astryx-theme-apple-color-blue-on-dark': ['#2997ff', '#2997ff'],
  '--astryx-theme-apple-color-on-primary': ['#ffffff', '#ffffff'],
  // The one shadow in the system — product imagery only.
  '--astryx-theme-apple-shadow-product': '3px 5px 30px 0 rgba(0, 0, 0, 0.22)',
};

export const appleTheme = defineTheme({
  name: 'apple',
  extends: neutralTheme,

  localTokens: appleLocalTokens,

  // ---------------------------------------------------------------------------
  // Typography — SF Pro Display for headlines, SF Pro Text for everything below
  // 20px. Scale: base 17 (Apple runs body at 17px, not 16), ratio 1.34, which
  // lands the ladder on 17 / 21 / 28 / 41 — Apple's 17 / 21 / 28 / 40.
  // ---------------------------------------------------------------------------
  typography: {
    scale: { base: 17, ratio: 1.34 },
    body: { family: SF_TEXT, fallbacks: SF_FALLBACKS, weight: '400' },
    heading: {
      family: SF_DISPLAY,
      fallbacks: SF_FALLBACKS,
      weight: '600',
      weights: { 1: '600', 2: '600', 3: '600', 4: '600', 5: '600', 6: '600' },
    },
    code: { family: 'ui-monospace', fallbacks: MONO_FALLBACKS },
  },

  motion: { fast: 140, medium: 350, slow: 800, ratio: 0.8 },

  tokens: {
    // -------------------------------------------------------------------------
    // Surfaces — pure white canvas over a parchment page; near-black inverted.
    // -------------------------------------------------------------------------
    '--color-background-surface': ['#ffffff', '#000000'],
    '--color-background-body': ['#f5f5f7', '#000000'],
    '--color-background-card': ['#ffffff', '#1d1d1f'],
    '--color-background-popover': ['#ffffff', '#1d1d1f'],
    '--color-background-muted': ['#f5f5f7', '#272729'],
    '--color-background-inverted': ['#1d1d1f', '#f5f5f7'],

    // -------------------------------------------------------------------------
    // Accent — Action Blue. Light: #0066cc. Dark/near-black: #2997ff.
    // -------------------------------------------------------------------------
    '--color-accent': ['#0066cc', '#2997ff'],
    '--color-accent-muted': ['rgba(0, 102, 204, 0.08)', 'rgba(41, 151, 255, 0.16)'],
    '--color-on-accent': ['#ffffff', '#ffffff'],
    '--color-text-accent': ['#0066cc', '#2997ff'],
    '--color-icon-accent': ['#0066cc', '#2997ff'],

    // -------------------------------------------------------------------------
    // Text / icon — one near-black ink on light, white on dark.
    // -------------------------------------------------------------------------
    '--color-text-primary': ['#1d1d1f', '#f5f5f7'],
    '--color-text-secondary': ['#7a7a7a', '#a1a1a6'],
    '--color-text-disabled': ['#7a7a7a', '#6e6e73'],
    '--color-on-dark': ['#ffffff', '#ffffff'],
    '--color-on-light': ['#1d1d1f', '#1d1d1f'],

    '--color-icon-primary': ['#1d1d1f', '#f5f5f7'],
    '--color-icon-secondary': ['#7a7a7a', '#a1a1a6'],
    '--color-icon-disabled': ['#7a7a7a', '#6e6e73'],

    // -------------------------------------------------------------------------
    // Hairlines — Apple borders, not Astryx's tinted borders.
    // -------------------------------------------------------------------------
    '--color-border': ['rgba(0, 0, 0, 0.08)', 'rgba(255, 255, 255, 0.12)'],
    '--color-border-emphasized': ['#d2d2d7', '#424245'],
    '--color-track': ['#e0e0e0', '#424245'],
    '--color-skeleton': ['#f0f0f0', '#2f2f31'],
    '--color-shadow': ['rgba(0, 0, 0, 0.22)', 'rgba(0, 0, 0, 0.5)'],

    // -------------------------------------------------------------------------
    // Radius — pill for actions, 18px for utility cards, 5px inline.
    // -------------------------------------------------------------------------
    '--radius-none': '0px',
    '--radius-inner': '5px',
    '--radius-element': '9999px',
    '--radius-container': '18px',
    '--radius-page': '18px',
    '--radius-chat': '18px',
    '--radius-full': '9999px',

    // -------------------------------------------------------------------------
    // Shadows — Apple ships exactly one, for product imagery. Cards, buttons and
    // text are flat; separation comes from surface colour and hairlines.
    // -------------------------------------------------------------------------
    '--shadow-low': 'none',
    '--shadow-med': 'none',
    '--shadow-high': '0 0 0 1px var(--color-border)',
    '--shadow-inset-hover': 'inset 0 0 0 2px rgba(0, 113, 227, 0.35)',
    '--shadow-inset-selected': 'inset 0 0 0 2px #0071e3',

    // -------------------------------------------------------------------------
    // Type ladder, pinned to the DESIGN.md scale.
    // -------------------------------------------------------------------------
    '--text-display-1-size': '3.5rem', // hero-display 56
    '--text-display-1-weight': '600',
    '--text-display-1-leading': '1.07',
    '--text-display-2-size': '3rem', // 48
    '--text-display-2-weight': '600',
    '--text-display-2-leading': '1.08',
    '--text-display-3-size': '2.125rem', // display-md 34
    '--text-display-3-weight': '600',
    '--text-display-3-leading': '1.1',

    '--text-heading-1-size': '2.5rem', // display-lg 40
    '--text-heading-1-weight': '600',
    '--text-heading-1-leading': '1.1',
    '--text-heading-2-size': '1.75rem', // lead 28
    '--text-heading-2-weight': '600',
    '--text-heading-2-leading': '1.14',
    '--text-heading-3-size': '1.3125rem', // tagline 21
    '--text-heading-3-weight': '600',
    '--text-heading-3-leading': '1.19',
    '--text-heading-4-size': '1.0625rem', // body-strong 17
    '--text-heading-4-weight': '600',
    '--text-heading-4-leading': '1.24',
    '--text-heading-5-size': '1.0625rem',
    '--text-heading-5-weight': '600',
    '--text-heading-5-leading': '1.24',
    '--text-heading-6-size': '0.875rem', // caption-strong 14
    '--text-heading-6-weight': '600',
    '--text-heading-6-leading': '1.29',

    '--text-body-size': '1.0625rem', // body 17
    '--text-body-weight': '400',
    '--text-body-leading': '1.47',
    '--text-large-size': '1.3125rem', // 21
    '--text-large-weight': '400',
    '--text-large-leading': '1.19',
    '--text-label-size': '0.875rem', // caption-strong 14
    '--text-label-weight': '600',
    '--text-label-leading': '1.29',
    '--text-code-size': '0.875rem',
    '--text-code-weight': '400',
    '--text-code-leading': '1.43',
    '--text-supporting-size': '0.75rem', // fine-print 12
    '--text-supporting-weight': '400',
    '--text-supporting-leading': '1.33',
  },

  components: {
    // -------------------------------------------------------------------------
    // Global nav: the only place pure black appears. 44px, white 12px links.
    // -------------------------------------------------------------------------
    'app-shell': {
      base: { backgroundColor: 'var(--astryx-theme-apple-color-parchment)' },
      'variant:elevated': {
        backgroundColor: 'var(--astryx-theme-apple-color-parchment)',
      },
    },
    'app-shell-header': {
      base: {
        backgroundColor: 'var(--astryx-theme-apple-color-black)',
        color: 'var(--astryx-theme-apple-color-body-on-dark)',
        '--color-text-primary': '#f5f5f7',
        '--color-text-secondary': '#cccccc',
        '--color-text-accent': '#f5f5f7',
        '--color-icon-primary': '#f5f5f7',
        '--color-icon-secondary': '#cccccc',
        '--color-border': 'rgba(255, 255, 255, 0.16)',
        '--color-overlay-hover': 'rgba(255, 255, 255, 0.08)',
        '--color-overlay-pressed': 'rgba(255, 255, 255, 0.16)',
        borderBottomWidth: '0',
      },
    },
    'top-nav': {
      base: {
        minHeight: 'var(--spacing-11)', // 44px
        height: 'var(--spacing-11)',
      },
    },

    // -------------------------------------------------------------------------
    // Type — negative tracking at display sizes ("Apple tight").
    // -------------------------------------------------------------------------
    heading: {
      base: { letterSpacing: '-0.01em' },
    },

    // -------------------------------------------------------------------------
    // Buttons — full-pill primary in Action Blue; press scales to 0.95.
    // -------------------------------------------------------------------------
    button: {
      base: {
        borderRadius: 'var(--radius-full)',
        fontWeight: '400',
        transition: 'transform var(--duration-fast) var(--ease-out)',
        ':active': { transform: 'scale(0.95)' },
      },
      'variant:primary': {
        backgroundColor: 'var(--astryx-theme-apple-color-blue)',
        color: 'var(--astryx-theme-apple-color-on-primary)',
        '--color-overlay-hover': 'rgba(255, 255, 255, 0.12)',
        '--color-overlay-pressed': 'rgba(255, 255, 255, 0.2)',
      },
      'variant:secondary': {
        backgroundColor: 'var(--astryx-theme-apple-color-pearl)',
        color: 'var(--astryx-theme-apple-color-blue)',
        borderColor: 'var(--astryx-theme-apple-color-blue)',
        borderWidth: 'var(--border-width)',
        borderStyle: 'solid',
      },
    },

    // -------------------------------------------------------------------------
    // Utility cards — white, 18px, hairline border, no shadow.
    // -------------------------------------------------------------------------
    card: {
      base: {
        borderRadius: 'var(--radius-container)',
        borderWidth: 'var(--border-width)',
        borderStyle: 'solid',
        borderColor: 'var(--color-border)',
        boxShadow: 'none',
        padding: 'var(--spacing-6)', // 24px
      },
      'variant:muted': {
        backgroundColor: 'var(--astryx-theme-apple-color-parchment)',
      },
      'variant:blue': {
        backgroundColor: 'var(--astryx-theme-apple-color-parchment)',
        borderColor: 'var(--astryx-theme-apple-color-blue)',
      },
    },

    section: {
      base: {
        borderRadius: 'var(--radius-container)',
        borderWidth: 'var(--border-width)',
        borderStyle: 'solid',
        borderColor: 'var(--color-border)',
        boxShadow: 'none',
        padding: 'var(--spacing-6)', // 24px
      },
      'variant:muted': {
        backgroundColor: 'var(--astryx-theme-apple-color-parchment)',
      },
    },

    banner: {
      base: {
        borderRadius: 'var(--radius-container)',
        boxShadow: 'none',
        borderWidth: 'var(--border-width)',
        borderStyle: 'solid',
        borderColor: 'var(--color-border)',
      },
    },

    // Pills, not rectangles: chips, tokens, badges, inputs, selects.
    badge: { base: { borderRadius: 'var(--radius-full)', fontWeight: '400' } },
    token: { base: { borderRadius: 'var(--radius-full)' } },
    'text-input': { base: { borderRadius: 'var(--radius-full)' } },
    selector: { base: { borderRadius: 'var(--radius-full)' } },

    'status-dot': {
      'variant:accent': { backgroundColor: 'var(--astryx-theme-apple-color-blue)' },
    },

    'progress-bar': {
      base: { '--color-background-muted': 'var(--color-track)' },
      'variant:accent': { '--color-accent': 'var(--astryx-theme-apple-color-blue)' },
    },

    divider: {
      base: { borderColor: 'var(--astryx-theme-apple-color-divider-soft)' },
    },

    'tab-list': {
      base: {
        '--color-accent': 'var(--astryx-theme-apple-color-blue)',
        '--color-text-accent': 'var(--astryx-theme-apple-color-blue)',
      },
    },

    'segmented-control': {
      base: { borderRadius: 'var(--radius-full)' },
    },
  },
});
